export const GET_ASTEROID_ID = "GET_ASTEROID_ID";
export const GET_ASTEROID_ID_FAILED = "GET_ASTEROID_ID_FAILED";
export const GET_ASTEROID_DETAILS = "GET_ASTEROID_DETAILS";
export const GET_ASTEROID_DETAILS_FAILED = "GET_ASTEROID_DETAILS_FAILED";
